# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('session_id', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('otp', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
        ),
    ]
